# Generated by Django 4.2.4 on 2025-04-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='nama',
            new_name='name',
        ),
    ]
